name: _
publish_to: none
environment:
  sdk: ^3.6.0
workspace:
  - packages/zenrouter
  - packages/zenrouter_core
  - packages/zenrouter_nocterm
  - packages/zenrouter_nocterm/example
  - packages/zenrouter/example
  - packages/zenrouter_devtools
  - packages/zenrouter_devtools/example
  - packages/zenrouter_file_generator
  - packages/zenrouter_file_generator/example
  - packages/zenrouter_file_annotation
  - packages/zenrouter/doc/paradigms/coordinator/example
  - packages/zenrouter_docs