name: zenrouter_nocterm
description: "A new Flutter package project."
version: 0.0.1
homepage:

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  nocterm: ^0.5.1
  zenrouter_core: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter